# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release do
    # add actions here: https://docs.fastlane.tools/actions
    versionNumber = prompt(text: "Version Number: ")
    buildNumber = prompt(text: "Build Number: ")

    increment_version_number(
      version_number:versionNumber,      # specify specific version number (optional, omitting it increments patch version number)
      xcodeproj: "./module-base/DemoBase.xcodeproj"  # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
    )
    
    increment_build_number(
      build_number: buildNumber, # specify specific build number (optional, omitting it increments by one)
      xcodeproj: "./module-base/DemoBase.xcodeproj" # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
    )

    commit_version_bump(
      xcodeproj: "./module-base/DemoBase.xcodeproj"  # optional, if you have multiple Xcode project files, you must specify your main project here
    )

    add_git_tag
  end
end
